Classes = [
    {
        'cid': '{d24d491f-820f-4d4d-b71f-900df0347aea}',
        'contract_ids': ['@camoufox.org/observer;1'],
        'esModule': 'resource://gre/modules/TrackingObserver.sys.mjs',
        'constructor': 'TrackingObserver',
        'categories': {'profile-after-change': 'TrackingObserver'},
    },
]
